use {
    std::{fs, io, path::Path, sync::Arc},
    tracing::{error, info, warn},
};

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub enum LogLevel {
    Trace,
    Debug,
    #[default]
    Info,
    Warn,
    Error,
    Critical,
}

impl LogLevel {
    fn parse(s: &str) -> Self {
        match s.to_lowercase().as_str() {
            "trace" => LogLevel::Trace,
            "debug" => LogLevel::Debug,
            "info" => LogLevel::Info,
            "warn" => LogLevel::Warn,
            "error" => LogLevel::Error,
            "critical" | "fatal" => LogLevel::Critical,
            _ => {
                warn!("Unknown loglevel '{}', falling back to info", s);
                LogLevel::Info
            }
        }
    }
}

impl std::fmt::Display for LogLevel {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            LogLevel::Trace => write!(f, "trace"),
            LogLevel::Debug => write!(f, "debug"),
            LogLevel::Info => write!(f, "info"),
            LogLevel::Warn => write!(f, "warn"),
            LogLevel::Error => write!(f, "error"),
            LogLevel::Critical => write!(f, "critical"),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ConfigSnapshot {
    pub check_freq: u32,
    pub cgroup_load: bool,
    pub type_load: bool,
    pub rule_load: bool,
    pub apply_nice: bool,
    pub apply_latnice: bool,
    pub apply_ioclass: bool,
    pub apply_ionice: bool,
    pub apply_sched: bool,
    pub apply_oom_score_adj: bool,
    pub apply_cgroups: bool,
    pub apply_cpuset: bool,
    pub cgroup_realtime_workaround: bool,
    pub x3d_mode: String,
    pub log_applied_rule: bool,
    pub loglevel: LogLevel,
}

impl Default for ConfigSnapshot {
    fn default() -> Self {
        Self {
            check_freq: 60,
            cgroup_load: true,
            type_load: true,
            rule_load: true,
            apply_nice: true,
            apply_latnice: true,
            apply_ioclass: true,
            apply_ionice: true,
            apply_sched: true,
            apply_oom_score_adj: true,
            apply_cgroups: true,
            apply_cpuset: true,
            cgroup_realtime_workaround: true,
            x3d_mode: "auto".to_string(),
            log_applied_rule: false,
            loglevel: LogLevel::default(),
        }
    }
}

impl ConfigSnapshot {
    pub fn parse_file<P: AsRef<Path>>(path: P) -> io::Result<Self> {
        let content = fs::read_to_string(&path)?;
        let mut config = Self::default();

        for line in content.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }

            if let Some((key, value)) = line.split_once('=') {
                let key = key.trim();
                let value = value.trim();

                match key {
                    "check_freq" => {
                        if let Ok(freq) = value.parse() {
                            config.check_freq = freq;
                        } else {
                            error!("Invalid check_freq value: {}", value);
                        }
                    }
                    "cgroup_load" => config.cgroup_load = value == "true",
                    "type_load" => config.type_load = value == "true",
                    "rule_load" => config.rule_load = value == "true",
                    "apply_nice" => config.apply_nice = value == "true",
                    "apply_latnice" => config.apply_latnice = value == "true",
                    "apply_ioclass" => config.apply_ioclass = value == "true",
                    "apply_ionice" => config.apply_ionice = value == "true",
                    "apply_sched" => config.apply_sched = value == "true",
                    "apply_oom_score_adj" => config.apply_oom_score_adj = value == "true",
                    "apply_cgroup" => config.apply_cgroups = value == "true",
                    "apply_cpuset" => config.apply_cpuset = value == "true",
                    "cgroup_realtime_workaround" => {
                        config.cgroup_realtime_workaround = value == "true"
                    }
                    "x3d_mode" => config.x3d_mode = value.to_string(),
                    "log_applied_rule" => config.log_applied_rule = value == "true",
                    "loglevel" => config.loglevel = LogLevel::parse(value),
                    _ => warn!("Unknown config key: {}", key),
                }
            }
        }

        Ok(config)
    }

    pub fn to_config_string(&self) -> String {
        format!(
            "# Generated by ananicy-rs\n\
            apply_nice={}\n\
            apply_sched={}\n\
            apply_ionice={}\n\
            apply_oom_score_adj={}\n\
            apply_latnice={}\n\
            log_applied_rule={}\n\
            cgroup_load={}\n\
            type_load={}\n\
            rule_load={}\n\
            cgroup_realtime_workaround={}\n\
            apply_cpuset={}\n\
            x3d_mode={}\n\
            loglevel={}\n\
            check_freq={}\n",
            self.apply_nice,
            self.apply_sched,
            self.apply_ionice,
            self.apply_oom_score_adj,
            self.apply_latnice,
            self.log_applied_rule,
            self.cgroup_load,
            self.type_load,
            self.rule_load,
            self.cgroup_realtime_workaround,
            self.apply_cpuset,
            self.x3d_mode,
            self.loglevel,
            self.check_freq
        )
    }
}

/// Thread-safe configuration manager
pub struct Config {
    snapshot: arc_swap::ArcSwap<ConfigSnapshot>,
}

impl Config {
    pub fn new(snapshot: ConfigSnapshot) -> Self {
        Self {
            snapshot: arc_swap::ArcSwap::from_pointee(snapshot),
        }
    }

    pub fn load_file<P: AsRef<Path>>(path: P, latnice_supported: bool) -> io::Result<Self> {
        let mut snapshot = match ConfigSnapshot::parse_file(&path) {
            Ok(s) => s,
            Err(ref e) if e.kind() == io::ErrorKind::NotFound => {
                error!("file {} does not exist", path.as_ref().display());
                let mut s = ConfigSnapshot::default();
                if !latnice_supported {
                    s.apply_latnice = false;
                }

                let config_string = s.to_config_string();

                info!("Default config:\n{}", config_string);
                info!("Writing default config to {}", path.as_ref().display());

                if path.as_ref().parent().is_some_and(|p| !p.exists() && fs::create_dir_all(p).is_err()) {
                    error!("Cannot create config directory {}", path.as_ref().parent().unwrap().display());
                }

                if let Err(write_err) = fs::write(&path, config_string) {
                    error!(
                        "Cannot write config to {}: {}",
                        path.as_ref().display(),
                        write_err
                    );
                }
                s
            }
            Err(e) => return Err(e),
        };

        if !latnice_supported {
            snapshot.apply_latnice = false;
        }
        Ok(Self::new(snapshot))
    }

    pub fn get(&self) -> arc_swap::Guard<Arc<ConfigSnapshot>> {
        self.snapshot.load()
    }

    pub fn reload_file<P: AsRef<Path>>(&self, path: P, latnice_supported: bool) -> io::Result<()> {
        let mut snapshot = ConfigSnapshot::parse_file(path)?;
        if !latnice_supported {
            snapshot.apply_latnice = false;
        }
        self.snapshot.store(Arc::new(snapshot));
        info!("Configuration reloaded");
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_defaults() {
        let config = ConfigSnapshot::default();
        assert_eq!(config.check_freq, 60);
        assert!(config.apply_nice);
        assert_eq!(config.x3d_mode, "auto");
    }

    #[test]
    fn test_parse_boolean_true() {
        let _config = ConfigSnapshot {
            apply_nice: false,
            ..Default::default()
        };
        // In this unit test we just test the logic, a file parsing test goes in differential test
    }

    #[test]
    fn test_load_writes_defaults_if_missing() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("missing.conf");
        let _config = Config::load_file(&path, true).unwrap();
        assert!(
            path.exists(),
            "load_file should write default config if it doesn't exist"
        );
        let content = fs::read_to_string(&path).unwrap();
        assert!(content.contains("cgroup_realtime_workaround=true"));
    }

    #[test]
    fn test_reload_disables_latnice_if_unsupported() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("reload.conf");
        fs::write(&path, "apply_latnice=true\n").unwrap();

        let config = Config::load_file(&path, true).unwrap();
        assert!(config.get().apply_latnice);

        // Reload but simulate kernel not supporting latnice anymore
        config.reload_file(&path, false).unwrap();
        assert!(
            !config.get().apply_latnice,
            "Reload should disable apply_latnice if unsupported"
        );
    }
}
