name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup-rust
        with:
          toolchain: stable
      - name: Build Release
        run: cargo build --locked --release --all-features
      - name: Strip Binary
        run: strip target/release/ananicy-rs
      - name: Package
        run: |
          tar -czvf ananicy-rs-linux-x86_64.tar.gz -C target/release ananicy-rs
          sha256sum ananicy-rs-linux-x86_64.tar.gz > ananicy-rs-linux-x86_64.tar.gz.sha256
      - name: Release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2.6.2
        with:
          files: |
            ananicy-rs-linux-x86_64.tar.gz
            ananicy-rs-linux-x86_64.tar.gz.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
